## Numpy Array and basics 
learn about numpy 

In [4]:
import numpy as np

### creating array from list

In [8]:
arr_1d = np.array([1,2,3,4,5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d Array is: ", arr_2d)

1D Array:  [1 2 3 4 5]
2d Array is:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [22]:
py_list = [1,2,3,3,4,5]
print("python list multiplication: ", py_list*2)


np_array = np.array([1,2,3,4,5])
print("numpy list multiplicatin: ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("python list time: ", time.time()-start)


start = time.time()
np_array = np.arange(1000000)*2
print("numpy operation time: ", time.time()-start)


python list multiplication:  [1, 2, 3, 3, 4, 5, 1, 2, 3, 3, 4, 5]
numpy list multiplicatin:  [ 2  4  6  8 10]
python list time:  0.15250420570373535
numpy operation time:  0.006127357482910156


### Creating arrays from scratch

In [ ]:
zeros = np.zeros((3,4))
print ("zeroes array: \n", zeros)

ones = np.ones((3,4))
print("ones array: \n", ones)

full = np.full((2,2), 7)
print("full array of 7 is: \n", full)

random = np.random.random((3,4))
print("random array is: \n", random)


sequence = np.arange(0, 10, 2)
print("sequence array is: \n", sequence)


zeroes array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array of 7 is: 
 [[7 7]
 [7 7]]
random matrix is: 
 [[0.48144535 0.97078014 0.44041339 0.78406199]
 [0.7561958  0.48205914 0.88642326 0.95993868]
 [0.30503483 0.71434569 0.84537787 0.87970989]]
random matrix is: 
 [0 2 4 6 8]


###VECTOR , MATRIX, TENSOR

In [32]:
vector = np.array([1,2,3])
print("vector is: \n", vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix is: \n", matrix)

tensor = np.array([[[1,2,3], [4,5,6]],
                   [[7,8,9], [10,11,12]]])
print("tensor is: \n", tensor)

vector is: 
 [1 2 3]
matrix is: 
 [[1 2 3]
 [4 5 6]]
tensor is: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### ARRAY PROPERTIES

In [5]:
array = np.array([[1,2,3],
                  [4,5,6.8]])
print("array shape: \n", array.shape)
print("array size: \n", array.size)
print("array dimension: \n", array.ndim)
print("array datatype: \n", array.dtype)

array shape: 
 (2, 3)
array size: 
 6
array dimension: 
 2
array datatype: 
 float64


### ARRAY  RESHAPING AND FLATTNING

In [7]:
arr = np.arange(12)
print("array is: \n", arr)

reshaped = arr.reshape((3,4))
print("reshaped array is: \n", reshaped)

flattened = reshaped.flatten()
print("flattened array is: \n", flattened)

#### transpose of matrix ke liye nothing but reshaped array is called with .T
transpose = reshaped.T
print("transposed array is: \n", transpose)

array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array is: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array is: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
transposed array is: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
