In [1]:
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("basic slicing: \n", arr[3:8])
print("basic slicing with gap: \n", arr[3:8:3])
print("negative indexing: \n", arr[-3])

basic slicing: 
 [4 5 6 7 8]
basic slicing with gap: 
 [4 7]
negative indexing: 
 8


### SAME OPERATIONS IN 2D AND 3D ARRAY

In [9]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element: \n", arr_2d[1,2])
print("entire row: \n", arr_2d[2])
print("entire colum: \n", arr_2d[:, 1])

specific element: 
 6
entire row: 
 [7 8 9]
entire colum: 
 [2 5 8]


### SORTING

In [16]:
unsorted = np.array([3,7,1,9,4,6,2,5,8])
print("sorted array is: \n", np.sort(unsorted))

# for 2d and 3d array
arr_2D_array = np.array([[3,7,1],
                         [9,4,6],
                        [2,5,8]])
print("original 2d array is: \n", arr_2D_array)
print("sorted 2d array is: \n", np.sort(arr_2D_array, axis = 1)) #sorting along rows
print("sorted 2d array is: \n", np.sort(arr_2D_array, axis = 0)) #sorting along columns

# for selected row only
print("sorted 2d array is: \n", np.sort(arr_2D_array[1])) #sorting along 2nd row
print("sorted 2d array is: \n", np.sort(arr_2D_array[:, 1])) #sorting along 2nd column

sorted array is: 
 [1 2 3 4 5 6 7 8 9]
original 2d array is: 
 [[3 7 1]
 [9 4 6]
 [2 5 8]]
sorted 2d array is: 
 [[1 3 7]
 [4 6 9]
 [2 5 8]]
sorted 2d array is: 
 [[2 4 1]
 [3 5 6]
 [9 7 8]]
sorted 2d array is: 
 [4 6 9]
sorted 2d array is: 
 [4 5 7]


### FILTER

In [17]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers%2 ==0]
print("even numbers of the array are: \n", even_numbers)

even numbers of the array are: 
 [ 2  4  6  8 10]


### FILTER WITH MASK

In [18]:
mask = numbers > 5
print("numbers greater than 5 is: \n", numbers[mask])

numbers greater than 5 is: 
 [ 6  7  8  9 10]


#### FANCY INDICES VS NP.WHERE()

In [21]:
indices = [0,2,4] 
print(numbers[indices])
where_result = np.where(numbers>5)
print(where_result) # this gives index of the where result
print("NP where",numbers[where_result])  ## this gives the actual values

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [23]:
condition_array = np.where(numbers>5, True, False)
print("condition array: \n", condition_array)

condition array: 
 [False False False False False  True  True  True  True  True]


#### ADDING DATA IN ARRAY

In [25]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined_arr = np.concatenate((arr1, arr2))
print("combined array: \n", combined_arr)

combined array: 
 [1 2 3 4 5 6]


ARRAY COMPATIBILITY

In [27]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("array compatiility: \n", a.shape == b.shape)


d = np.array([1,2,3])
e = np.array([4,5,6,7])     # i have changes this array size to make it incompatible
f = np.array([7,8,9])
print("array compatiility: \n", d.shape == e.shape)


array compatiility: 
 True
array compatiility: 
 False


#### ADDING HORIZONTALLY AND VERTICALLY

In [35]:
original = np.array([[1,2,3], [4,5,6]])
new_row = np.array([[7, 8, 9]])

with_new_row = np.vstack((original, new_row))
print("original array: \n", original)
print("with new row: \n", with_new_row)

new_column = np.array([[10], [11]])
with_new_column = np.hstack((original, new_column))
print("original array: \n", original)
print("with new column: \n", with_new_column)

original array: 
 [[1 2 3]
 [4 5 6]]
with new row: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
original array: 
 [[1 2 3]
 [4 5 6]]
with new column: 
 [[ 1  2  3 10]
 [ 4  5  6 11]]


##### DELETING OPERATIONS ON ARRAY

In [36]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print("array after deletion: \n", deleted)

array after deletion: 
 [1 2 4 5]
